### ISSUE TITLE
Collect feedback

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlClientExtensions#5]
Hi @roji - I know you are busy, bt would be grateful to have your valuable opinion if this will add any value to the .NET Data ecosystem. 

(Or if it is better to wait for SqlClient to add all this, as it has access to internals)

**Comment by roji** [comment]
Nice idea @ErikEJ :)

Note that the System.Data DbDataSource already provides a default DbDataSource implementation which anyone can use without the driver implementing anything; that's acquired via [DbProviderFactory.CreateDataSource](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Data.Common/src/System/Data/Common/DbProviderFactory.cs#L70). Of course, that only supports the connection string, and doesn't provide any nice, provider-specific APIs like what I showed for Npgsql.

I think the main question here is whether you think you can actually add useful, SqlClient-specific functionality on your DbDataSource, without changing SqlClient internals (i.e. #3); like logging wouldn't be possible. If not, then I'm not sure there's value in a SqlDataSource that only supports the connection string - people can just use the default one from System.Data in that case.

One orthogonal thing is adding the DI integration (e.g. AddSqlDataSource). That's indeed something you could do externally, just to make things nicer for DI users, and it doesn't belong inside SqlClient because of the DI dependency (just like in Npgsql we have Npgsql.DependencyInjection as an external package). But an actual SqlDataSource implementation is a different thing.

PS Your README.md still contains traces of PostgreSQL :smiling_imp:

**Comment by ErikEJ** [comment]
As noted, logging is actually added.

**Comment by ajcvickers** [comment]
Looks useful to me.

**Comment by ErikEJ** [comment]
Thanks @ajcvickers  and @roji, I will create a blog post and publish an alpha to Nuget in the near future.

**Comment by roji** [comment]
Looks useful to me too.
